[package]
name = "tx-compiler"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["assembly/std", "crypto/std", "miden-core/std"]

[dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "next", default-features = false }
crypto = { package = "miden-crypto", version = "0.5", default-features = false }
hashbrown = { version = "0.13.2" }
miden-core = { package = "miden-core", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "next", default-features = false }
miden-objects = { package = "miden-objects", path = "../objects"}